/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppIsBroken() {
        App classUnderTest = new App();
        throw new RuntimeException("she is broken");
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
